### ISSUE TITLE
Failure to parse chunked responses from older scylla versions (5.0)

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla-api-client#43]
When trying to connect to an older version of scylla (tested with 5.0.1), I get a failure (see below). I can connect to recent version (master) just fine.

Error:
```
# scylla-api-client  -lm
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 696, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 763, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 792, in read_chunked
    self._original_response.close()
  File "/usr/lib64/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scylla-api-client", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/cli.py", line 95, in main
    scylla_api = load_api(node_address=node_address, port=port)
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/cli.py", line 59, in load_api
    scylla_api.load()
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/api.py", line 390, in load
    module_json = self.client.get_raw_api_json(f"{module_def['path']}/")
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/rest/scylla_rest_client.py", line 11, in get_raw_api_json
    if api := self.get(f"/api-doc{resource_path}"):
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/rest/scylla_rest_client.py", line 16, in get
    return super().get(resource_path=resource_path, query_params=query_params)
  File "/usr/local/lib/python3.9/site-packages/scylla_api_client/rest/__init__.py", line 69, in get
    return requests.get(url=url, params=query_params, headers=headers)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by denesb** [comment]
Actually, I can connect to the service with `curl` just fine, but `scylla-api-client` fails as shown above.

**Comment by denesb** [comment]
This is happening inside a docker (scylla's dbuild) container.

**Comment by denesb** [comment]
Looks like this could be buggy HTTP chunked transfer implementation.
See https://github.com/psf/requests/issues/5583 and https://github.com/psf/requests/issues/4248.
cc @nyh

**Comment by denesb** [comment]
Scylla version is 5.0.1, I can connect to master just fine. Was there a bug fixed related to chunked encoding between 5.0.1 and master?

**Comment by denesb** [comment]
HTTP Headers look identical between `5.0.1` and master:
```
HTTP/1.1 200 OK
Content-Length: 1224
Content-Type: application/json
Date: Thu, 08 Sep 2022 03:55:13 GMT
Server: Seastar httpd
```

**Comment by bhalevy** [comment]
Sounds like we could benefit from adding a seastar test that uses the python client to test the seastar http server.

**Comment by denesb** [comment]
Yes, but I still couldn't find out what exactly is different between the two versions (5.0.1 and master). `scylla-api-client` only works with the latter, but the browser and `curl` works with both.
The relevant part of the `urllib` code (as far as I can tell) looks the same too.
I checked the commits related to httpd in seastar and didn't see anything relevant.

I hope @nyh might have a hunch.

**Comment by nyh** [comment]
> Sounds like we could benefit from adding a seastar test that uses the python client to test the seastar http server.

I'm trying to look now if I can find any explanation for this bug (or why it disappeared in master). You're absolutely right that Seastar's HTTP server needs separate testing - and a lot more of it.

**Comment by nyh** [comment]
> HTTP Headers look identical between `5.0.1` and master:
> 
> ```
> HTTP/1.1 200 OK
> Content-Length: 1224
> Content-Type: application/json
> Date: Thu, 08 Sep 2022 03:55:13 GMT
> Server: Seastar httpd
> ```

These headers suggest that chunked encoding was **not** used in the reply, so it's weird that we belive the bug was in chunked encoding. I'll try to reproduce this myself.

**Comment by denesb** [comment]
> so it's weird that we belive the bug was in chunked encoding

The two issues I found with quick googling suggested as much. I admit I didn't dig into the problem much further, as I'm not familiar with the internals of the HTTP protocol.
If you found the real root cause, I will update the title/description, so anybody searching for this error in the future is not mislead.

**Comment by denesb** [comment]
Actually `curl` also breaks down with a more complex request, like:
```
$ curl http://127.0.0.1:10000/api-doc/system/ -vvv
*   Trying 127.0.0.1:10000...
* Connected to 127.0.0.1 (127.0.0.1) port 10000 (#0)
> GET /api-doc/system/ HTTP/1.1
> Host: 127.0.0.1:10000
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: application/json
< Date: Thu, 08 Sep 2022 06:21:23 GMT
< Server: Seastar httpd
< 
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```
This request works on master bu fails on 5.0.1.

**Comment by nyh** [comment]
I just built 5.0.1 on my machine and tried this request, and it worked to completion... After the headers as in your output, I get the actual output:
```
{
   "apiVersion":"0.0.1",
   "swaggerVersion":"1.2",
```

It looks like Scylla is indeed using chunked encoding (notice the "Transfer-Encoding: chunked") and in your version Scylla did not send the first chunk, or sent it incorrectly?

I tried manual "telnet" to see the protocol without curl confusing me:
```
$ telnet 127.0.0.1 10000
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /api-doc/system/ HTTP/1.1               <------ type this line, and follow by another empty line

```
The result:
```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json
Date: Thu, 08 Sep 2022 06:29:16 GMT
Server: Seastar httpd

1053
{
   "apiVersion":"0.0.1",
...
}

0

```

Note how the chunked encoding is output correctly - there is one chunk of 1053 bytes, and then a final chunk of 0 bytes - as expected. Can you please try this "telnet" thing and tell me what it looks like in your broken version?

(I'm starting to wonder if I compiled 5.0.1 incorrectly, I'll try again...)

**Comment by nyh** [comment]
I also checked that "scylla-api-client -lm" also works for me on Scylla 5.0.1...
I did the following to build it:
```
git checkout scylla-5.0.1
git submodule update
rm -r build
dbuild ./configure.py --disable-dpdk
dbuild ninja build/dev/scylla
```

**Comment by nyh** [comment]
By the way, @denesb, do you see anything in **Scylla**'s log? Maybe there is some sort of error in the REST API server and it simply aborts the connection in the middle of generating a response, and the error is only visible in the Scylla log.

Scylla should probably close the connection more gracefully on an error and not confuse the client (namely, if it already sent a chunked encoding header, it must send an empty chunk to end the connection - it shouldn't just close the connection immediately), but that would be a relatively minor bug compared to why the request aborted in the first place.

**Comment by denesb** [comment]
```
# telnet 127.0.0.1:10000
telnet: 127.0.0.1:10000: Name or service not known
127.0.0.1:10000: Unknown host
[root@fedora scylla-cli]# telnet 127.0.0.1 10000
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /api-doc/system/ HTTP/1.1

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json
Date: Thu, 08 Sep 2022 07:10:38 GMT
Server: Seastar httpd

Connection closed by foreign host.
```
Nothing in the scylla logs.

**Comment by denesb** [comment]
This worked:
```
$ telnet 127.0.0.1 10000
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET /api-doc/ HTTP/1.1               

HTTP/1.1 200 OK
Content-Length: 1145
Content-Type: application/json
Date: Thu, 08 Sep 2022 07:12:32 GMT
Server: Seastar httpd

{"apiVersion": "0.0.1", "swaggerVersion": "1.2", "apis": [{"path": "/system", "description": "The system related API"},{"path": "/compaction_manager", "description": "The Compaction manager API"},{"path": "/gossiper", "description": "The gossiper API"},{"path": "/endpoint_snitch_info", "description": "The endpoint snitch info API"},{"path": "/storage_proxy", "description": "The storage proxy API"},{"path": "/column_family", "description": "The column family API"},{"path": "/stream_manager", "description": "The stream manager API"},{"path": "/messaging_service", "description": "The messaging service API"},{"path": "/storage_service", "description": "The storage service API"},{"path": "/cache_service", "description": "The cache service API"},{"path": "/failure_detector", "description": "The failure detector API"},{"path": "/hinted_handoff", "description": "The hinted handoff API"},{"path": "/lsa", "description": "Log-structured allocator API"},{"path": "/commitlog", "description": "The commit log API"},{"path": "/collectd", "description": "The collectd API"},{"path": "/error_injection", "description": "The error injection API"}]}
```

**Comment by denesb** [comment]
I don't know if this is relevant or not but I'm not running scylla in the build directory, so its not reading the default config (in `conf/scylla.yaml`). I will try running it in the repo to see if it makes a difference.

**Comment by denesb** [comment]
Ok, running the very same scylla from the repo works. It must be something I passed (or didn't pass) on the command line.

**Comment by nyh** [comment]
I suspect that something in the /api-doc/system/ request is failing and abruptly closing the connection (which is a secondary bug...) but I don't know why it would fail silently without printing anything in the log. 

I also don't use configuration files. My Scylla command line:
```
tools/toolchain/dbuild ./build/dev/scylla --skip-wait-for-gossip-to-settle 0 --developer-mode=1 --ring-delay-ms 4000 --collectd 0 --logger-log-level alternator-server=trace --logger-log-level alternator-executor=trace --cpuset 0 -m 1G --api-address 127.0.0.1 --rpc-address 127.0.0.1 --listen-address 127.0.0.1 --prometheus-address 127.0.0.1 --seed-provider-parameters seeds=127.0.0.1 --datadir /home/nyh/scylla/tmp/1/data --commitlog-directory /home/nyh/scylla/tmp/1/commitlog --hints-directory /home/nyh/scylla/tmp/1/hints --view-hints-directory /home/nyh/scylla/tmp/1/view_hints --experimental-features=cdc --alternator-port=8000 --alternator-address 127.0.0.1 --alternator-enforce-authorization=0 --alternator-write-isolation=always
```

**Comment by denesb** [comment]
I think this is the problem:
```
  32 [pid   683] openat(AT_FDCWD, "api/api-doc/system.json", O_RDONLY|O_CLOEXEC) = 90 
```
Since I'm not running scylla in the repo, it cannot open this file and produce the output.

**Comment by nyh** [comment]
By the way, https://stackoverflow.com/questions/4179750/aborting-a-http-1-1-chunk-encoded-response and https://stackoverflow.com/questions/17203379/response-sent-in-chunked-transfer-encoding-and-indicating-errors-happening-after suggest that if the server is in the middle of generating a chunked-encoding response and fails, the right thing to do is to close the connection - without sending the last zero-length chunk - and the client should handle that as an error. It's ugly but it's the right behavior. Scylla is doing the right thing by closing the connection.

The remaining problems we have now:
1. Why did the request fail (but I see now you found the problem, api/api-doc/system.json, great).
2. Why wasn't there anything in the log about why the request failed
3. We should consider avoiding chunked encoding for short reponses. As we saw now, chunked encoding really sucks in error cases.

Let me know which of these you intend to open as issues and I'll open the rest ;-)

**Comment by nyh** [comment]
> Thanks for helping me get to the bottom of this. I've been using scylla out-of tree to simulate small clusters without docker (just running them all on my host binding to different 127.0.0.x IP) and this has been bugging me for a long time, only now reaching a boiling point, prompting me look into it.

I also have such a script ;-) Also test/cql-pytest/run.py is an improved version of that script.
I probably never noticed the specific problem you mentioned because usually my current directory **is** a Scylla tree, so that file exists.

**Comment by denesb** [comment]
Closing this issue. Strictly speaking there is no bug here: scylla simply fails to generate a response due to the missing api-doc files and abruptly closes the connection (which is allowed). The client however interprets this as an error and complains loudly because the expected last 0-length chunk is missing from the chunked response. Both the server and the client are in the right, still the result is a confusing and misleading error on the client side and silence in the scylla logs.
